### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by warapitiya** [ghoullier/angular-with-lerna#1]
Is this project active? By the look of it, this uses old dependencies. Could you update this?

**Comment by ghoullier** [comment]
Hi!
Indeed this project is no longer active. It's was an playground project to experiment lerna and angular.
If you want to share some code between angular apps and angular libraries in a monorep project, you can try https://github.com/nrwl/nx

**Comment by warapitiya** [comment]
Yes. That's what I'm already using. Just wondering other possibilities! :D

**Comment by ghoullier** [comment]
I've encountered some problems with AoT and lerna. That's why I stop to maintain this project, but if I found some time to investigate deeper on this issues, I will probably update this project.
